server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.189.130:3306/agrotechnical?characterEncoding=utf-8
    username: root
    password: guoleisong01
  jpa:
    database: mysql
    show-sql: true